_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 54
                - 55
            "2":
                - 1
                - 54
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
dataset:
    value: dataset_10M.csv
preparation_name:
    value: preparation_10M_9
sampling_config:
    value:
        compile: true
        device: cuda
        seed: 1337
        temperature: 0.8
        top_k: 200
training_config:
    value:
        batch_size: 128
        beta2: 0.98
        context_events: 1
        dropout: 0.1
        eval_interval: 250
        eval_iters: 200
        gradient_accumulation_steps: 80
        learning_rate: 0.001
        log_interval: 10
        lr_decay_iters: 5000
        max_iters: 1000000
        max_num_failed_checkpoint_checks: 8
        min_lr: 1e-05
        n_embd: 1024
        n_head: 128
        n_layer: 48
        warmup_iters: 250
